# WiFi Settings
CIRCUITPY_WIFI_SSID = "your_wifi_ssid"
CIRCUITPY_WIFI_PASSWORD = "your_wifi_password"

# Adafruit IO Settings
ADAFRUIT_IO_USERNAME = "your_adafruit_io_username"
ADAFRUIT_IO_KEY = "your_adafruit_io_key"
ADAFRUIT_IO_FEED_NAME = "distance-sensor"

# Time Settings (in seconds)
DISTANCE_MONITOR_REPORT_INTERVAL = 10800     # 3 hours - maximum time between reports
DISTANCE_MONITOR_MIN_REPORT_INTERVAL = 86400 # 24 hours - minimum time between reports 
DISTANCE_MONITOR_AWAKE_TIME = 30             # Time to stay awake after button press

# Sensor Settings
DISTANCE_MONITOR_DEFAULT_HYSTERESIS = 2.0    # Default sensitivity threshold in cm
DISTANCE_MONITOR_MIN_HYSTERESIS = 0.5        # Minimum sensitivity threshold in cm
DISTANCE_MONITOR_MAX_HYSTERESIS = 10.0       # Maximum sensitivity threshold in cm
DISTANCE_MONITOR_MAX_STORED_READINGS = 5     # Number of previous readings to store